language: python
python:
  - "3.6"
install:
  - pip install cookiecutter
script:
  - cookiecutter . --no-input --overwrite-if-exists
  - pip install -r my_django_project/requirements/testing.txt
  - pytest my_django_project/
