version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    user: django
    depends_on:
      - postgres
    command: /gunicorn.sh
    env_file: .env

  caddy:
    build: ./docker/caddy
    depends_on:
      - django
    ports:
      - 80:80
      - 443:443
