version: '2'

services:
  postgres:
    build: ./docker/postgres
    environment:
      - POSTGRES_USER=postgres

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile-test
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.testing
      - POSTGRES_USER=postgres
    links:
      - postgres
